# Generated by Django 5.0.7 on 2024-08-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_failedjob_feedback_inquiry_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
