# Generated by Django 5.0.7 on 2024-08-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_options_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
